### PR TITLE
Homework #0

### PR DESCRIPTION
**Pull request by camzillajs101**
Camilo’s Nano Hacker homework 0!

### CODE REVIEW

**Comment by camzillajs101** [comment]
@rickyc
My pull request has been completed!

**Comment by rickyc** [comment]
Looks good. Make another change to the file and commit it :)

**Comment by camzillajs101** [comment]
Should I merge it?

**Comment by camzillajs101** [comment]
@rickyc (above message)

**Comment by rickyc** [comment]
The answer is no, you should not have merged it yet. You didn't make a
second commit as I asked you to.

**Pull request merged**
